import axios from 'axios';

const API_BASE_URL = import.meta.env.VITE_API_URL;
const MOCK_MODE = import.meta.env.VITE_MOCK_API === 'true';

const api = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Mock responses
const MOCK_RESPONSES = {
  GREEN: {
    assessment_id: "demo-001",
    triage_level: "GREEN",
    confidence_score: 82,
    symptoms_detected: ["Mild fever", "Common cold", "Fatigue"],
    primary_concern: "Upper respiratory infection",
    recommended_action: "Rest at home, drink fluids, paracetamol for fever",
    urgency_reason: "Mild viral infection, no red flag symptoms",
    follow_up_questions: ["Fever above 103F?", "Breathing difficulty?"]
  },
  YELLOW: {
    assessment_id: "demo-002",
    triage_level: "YELLOW",
    confidence_score: 88,
    symptoms_detected: ["High fever 103F", "Severe headache", "Body pain", "Skin rash"],
    primary_concern: "Possible Dengue Fever",
    recommended_action: "Visit PHC within 24 hours, get blood test, drink ORS",
    urgency_reason: "Classic dengue warning signs, needs platelet monitoring",
    follow_up_questions: ["Bleeding from gums?", "Vomiting?", "Platelet count?"]
  },
  RED: {
    assessment_id: "demo-003",
    triage_level: "RED",
    confidence_score: 96,
    symptoms_detected: ["Chest pain", "Left arm pain", "Breathing difficulty", "Sweating"],
    primary_concern: "SUSPECTED HEART ATTACK - Cardiac Emergency",
    recommended_action: "CALL 108 IMMEDIATELY. Keep patient still. Give aspirin if available.",
    urgency_reason: "Classic cardiac emergency symptoms, every minute is critical",
    follow_up_questions: ["Is patient conscious?", "Known heart condition?", "Time since onset?"]
  }
};

const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

export const submitAssessment = async (data) => {
  if (MOCK_MODE) {
    await delay(2000);
    const mockLevel = data.mockLevel || 'GREEN';
    return { data: MOCK_RESPONSES[mockLevel] };
  }
  return api.post('/triage', data);
};

export const generateReport = async (assessmentId) => {
  if (MOCK_MODE) {
    await delay(1500);
    return {
      data: {
        report_url: 'mock-report-url',
        report_html: `
          <div style="font-family: Arial, sans-serif; padding: 20px;">
            <h1 style="color: #16a34a;">AyushScan AI - Medical Report</h1>
            <p><strong>Assessment ID:</strong> ${assessmentId}</p>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
            <h2>Triage Assessment</h2>
            <p>This is a mock report generated for demonstration purposes.</p>
            <p><strong>Recommendation:</strong> Follow up with healthcare provider.</p>
            <div style="margin-top: 30px; padding: 10px; background: #f0f0f0; border-radius: 5px;">
              <small>Generated by Amazon Nova Pro on AWS Bedrock</small>
            </div>
          </div>
        `
      }
    };
  }
  return api.post('/report', { assessment_id: assessmentId });
};

export const getUploadUrl = async () => {
  if (MOCK_MODE) {
    await delay(500);
    return {
      data: {
        upload_url: 'mock-upload-url',
        s3_key: `mock-${Date.now()}.jpg`
      }
    };
  }
  return api.get('/upload-url');
};

export const getAssessments = async () => {
  if (MOCK_MODE) {
    await delay(800);
    return {
      data: {
        assessments: [
          MOCK_RESPONSES.GREEN,
          MOCK_RESPONSES.YELLOW,
          MOCK_RESPONSES.RED
        ]
      }
    };
  }
  return api.get('/assessments');
};

export default api;
