import axios from 'axios';

const BASE_URL = import.meta.env.VITE_API_URL || '';

const api = axios.create({
  baseURL: BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Fallback mock responses for when API is unavailable
const FALLBACK_RESPONSES = {
  mild: {
    assessment_id: `fallback-${Date.now()}`,
    triage_level: "GREEN",
    confidence_score: 82,
    symptoms_detected: ["Mild fever", "Common cold", "Fatigue"],
    primary_concern: "Upper Respiratory Infection",
    recommended_action: "Rest at home, drink fluids, paracetamol for fever",
    urgency_reason: "Mild viral infection, no red flag symptoms",
    follow_up_questions: ["Has the fever exceeded 102°F?", "Any difficulty breathing?"]
  },
  moderate: {
    assessment_id: `fallback-${Date.now()}`,
    triage_level: "YELLOW",
    confidence_score: 88,
    symptoms_detected: ["High fever", "Severe headache", "Body pain", "Skin rash"],
    primary_concern: "Possible Dengue Fever",
    recommended_action: "Visit clinic within 24 hours, get dengue blood test",
    urgency_reason: "Classic dengue pattern — fever, joint pain, rash combination",
    follow_up_questions: ["When did the rash first appear?", "Any bleeding from gums or nose?"]
  },
  severe: {
    assessment_id: `fallback-${Date.now()}`,
    triage_level: "RED",
    confidence_score: 96,
    symptoms_detected: ["Chest pain", "Left arm pain", "Difficulty breathing", "Heavy sweating"],
    primary_concern: "Suspected Cardiac Emergency",
    recommended_action: "CALL 108 IMMEDIATELY — suspected heart attack",
    urgency_reason: "Multiple classic cardiac warning signs present simultaneously",
    follow_up_questions: ["Is the chest pain crushing or pressure-like?", "Is patient conscious?"]
  }
};

const analyzeSymptomsLocally = (symptomsText) => {
  const text = symptomsText.toLowerCase();
  
  // Check for emergency keywords
  if (text.includes('chest pain') || text.includes('heart') || 
      text.includes('unconscious') || text.includes('seizure') ||
      text.includes('severe bleeding') || text.includes('can\'t breathe')) {
    return 'severe';
  }
  
  // Check for moderate keywords
  if (text.includes('high fever') || text.includes('103') || text.includes('104') ||
      text.includes('severe headache') || text.includes('rash') ||
      text.includes('vomiting') || text.includes('diarrhea')) {
    return 'moderate';
  }
  
  // Default to mild
  return 'mild';
};

export const submitAssessment = async (data) => {
  const requestBody = {
    patient_name: data.patient?.name || 'Unknown',
    patient_age: data.patient?.age || 'Unknown',
    patient_location: data.patient?.location || 'Unknown',
    symptoms_text: data.voice?.transcript || '',
    image_analysis: data.image?.s3Key || '',
    language: data.voice?.language || 'en',
  };
  
  try {
    const response = await api.post('/triage', requestBody, { timeout: 30000 });
    return { data: response.data };
  } catch (error) {
    console.error('API call failed:', error);
    
    // Fallback to local analysis
    const severity = analyzeSymptomsLocally(requestBody.symptoms_text);
    const fallbackResponse = FALLBACK_RESPONSES[severity];
    
    console.log('Using fallback response due to API error');
    return { data: fallbackResponse };
  }
};

export const generateReport = async (assessmentId) => {
  try {
    const response = await api.post('/report', {
      assessment_id: assessmentId,
    }, { timeout: 30000 });
    return { data: response.data };
  } catch (error) {
    console.error('Report generation failed:', error);
    // Return fallback report
    return {
      data: {
        report_url: 'fallback-report',
        report_html: `
          <div style="font-family: Arial, sans-serif; padding: 20px;">
            <h1 style="color: #16a34a;">AyushScan AI - Medical Report</h1>
            <p><strong>Assessment ID:</strong> ${assessmentId}</p>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
            <h2>Triage Assessment</h2>
            <p>This is a fallback report generated for demonstration purposes.</p>
            <p><strong>Recommendation:</strong> Follow up with healthcare provider.</p>
            <div style="margin-top: 30px; padding: 10px; background: #f0f0f0; border-radius: 5px;">
              <small>Generated by AyushScan AI</small>
            </div>
          </div>
        `
      }
    };
  }
};

export const getAssessments = async () => {
  try {
    const response = await api.get('/assessments');
    return { data: response.data };
  } catch (error) {
    console.error('Get assessments failed:', error);
    return { data: { assessments: [] } };
  }
};

export const getUploadUrl = async (filename, contentType) => {
  try {
    const response = await api.get('/upload-url', {
      params: { filename, content_type: contentType }
    });
    return { data: response.data };
  } catch (error) {
    console.error('Get upload URL failed:', error);
    return {
      data: {
        upload_url: 'fallback-url',
        s3_key: `fallback-${Date.now()}.jpg`
      }
    };
  }
};

export default api;
