import axios from 'axios';

const API_BASE_URL = import.meta.env.VITE_API_URL;
const MOCK_MODE = import.meta.env.VITE_MOCK_API === 'true' || 
                  import.meta.env.VITE_MOCK_API === true ||
                  String(import.meta.env.VITE_MOCK_API).toLowerCase() === 'true';

const api = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Module-level variable to track current mock type
let currentMockType = 'green';

// Export function to set mock type
export const setMockType = (type) => {
  currentMockType = type.toLowerCase();
};

// Mock responses for demo mode only
const MOCK_RESPONSES = {
  green: {
    assessment_id: "demo-green-001",
    triage_level: "GREEN",
    confidence_score: 82,
    symptoms_detected: ["Mild fever", "Common cold", "Fatigue"],
    primary_concern: "Upper Respiratory Infection",
    recommended_action: "Rest at home, drink fluids, paracetamol for fever",
    urgency_reason: "Mild viral infection, no red flag symptoms",
    follow_up_questions: ["Has the fever exceeded 102°F?", "Any difficulty breathing?"]
  },
  yellow: {
    assessment_id: "demo-yellow-002",
    triage_level: "YELLOW",
    confidence_score: 88,
    symptoms_detected: ["High fever 103°F", "Severe headache", "Body pain", "Skin rash"],
    primary_concern: "Possible Dengue Fever",
    recommended_action: "Visit clinic within 24 hours, get dengue blood test",
    urgency_reason: "Classic dengue pattern — fever, joint pain, rash combination",
    follow_up_questions: ["When did the rash first appear?", "Any bleeding from gums or nose?"]
  },
  red: {
    assessment_id: "demo-red-003",
    triage_level: "RED",
    confidence_score: 96,
    symptoms_detected: ["Chest pain", "Left arm pain", "Difficulty breathing", "Heavy sweating", "Confusion"],
    primary_concern: "Suspected Cardiac Emergency",
    recommended_action: "CALL 108 IMMEDIATELY — suspected heart attack",
    urgency_reason: "Multiple classic cardiac warning signs present simultaneously",
    follow_up_questions: ["Is the chest pain crushing or pressure-like?", "Is patient conscious?"]
  }
};

const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

export const submitAssessment = async (data) => {
  // Use mock mode ONLY for quick demos
  if (MOCK_MODE) {
    await delay(2000);
    return { data: MOCK_RESPONSES[currentMockType] || MOCK_RESPONSES['green'] };
  }
  
  // Real API call with actual symptom analysis
  try {
    const requestBody = {
      patient_info: {
        name: data.patient?.name || '',
        age: data.patient?.age ? parseInt(data.patient.age) : null,
        gender: data.patient?.gender || '',
        location: data.patient?.location || ''
      },
      voice_transcript: data.voice?.transcript || '',
      image_s3_key: data.image?.s3Key || null
    };
    
    console.log('Submitting to real API:', requestBody);
    
    const response = await api.post('/triage', requestBody, { timeout: 30000 });
    return { data: response.data };
  } catch (error) {
    console.error('API failed:', error);
    // Fallback to mock for demo purposes
    await delay(1000);
    return { data: MOCK_RESPONSES[currentMockType] || MOCK_RESPONSES['green'] };
  }
};

export const generateReport = async (assessmentId) => {
  if (MOCK_MODE) {
    await delay(1500);
    return {
      data: {
        report_url: 'mock-report-url',
        report_html: `
          <div style="font-family: Arial, sans-serif; padding: 20px;">
            <h1 style="color: #16a34a;">AyushScan AI - Medical Report</h1>
            <p><strong>Assessment ID:</strong> ${assessmentId}</p>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
            <h2>Triage Assessment</h2>
            <p>This is a mock report generated for demonstration purposes.</p>
            <p><strong>Recommendation:</strong> Follow up with healthcare provider.</p>
            <div style="margin-top: 30px; padding: 10px; background: #f0f0f0; border-radius: 5px;">
              <small>Generated by Amazon Nova Pro on AWS Bedrock</small>
            </div>
          </div>
        `
      }
    };
  }
  
  try {
    const response = await api.post('/report', { assessment_id: assessmentId }, { timeout: 15000 });
    return { data: response.data };
  } catch (error) {
    console.error('Report API failed, falling back to mock:', error);
    await delay(1000);
    return {
      data: {
        report_url: 'mock-report-url',
        report_html: `
          <div style="font-family: Arial, sans-serif; padding: 20px;">
            <h1 style="color: #16a34a;">AyushScan AI - Medical Report</h1>
            <p><strong>Assessment ID:</strong> ${assessmentId}</p>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
            <h2>Triage Assessment</h2>
            <p>This is a mock report generated for demonstration purposes.</p>
            <p><strong>Recommendation:</strong> Follow up with healthcare provider.</p>
            <div style="margin-top: 30px; padding: 10px; background: #f0f0f0; border-radius: 5px;">
              <small>Generated by Amazon Nova Pro on AWS Bedrock</small>
            </div>
          </div>
        `
      }
    };
  }
};

export const getUploadUrl = async () => {
  if (MOCK_MODE) {
    await delay(500);
    return {
      data: {
        upload_url: 'mock-upload-url',
        s3_key: `mock-${Date.now()}.jpg`
      }
    };
  }
  
  try {
    const response = await api.get('/upload-url', { timeout: 10000 });
    return { data: response.data };
  } catch (error) {
    console.error('Upload URL API failed, falling back to mock:', error);
    await delay(500);
    return {
      data: {
        upload_url: 'mock-upload-url',
        s3_key: `mock-${Date.now()}.jpg`
      }
    };
  }
};

export const getAssessments = async () => {
  if (MOCK_MODE) {
    await delay(800);
    return {
      data: {
        assessments: [
          MOCK_RESPONSES.green,
          MOCK_RESPONSES.yellow,
          MOCK_RESPONSES.red
        ]
      }
    };
  }
  
  try {
    const response = await api.get('/assessments', { timeout: 10000 });
    return { data: response.data };
  } catch (error) {
    console.error('Assessments API failed, falling back to mock:', error);
    await delay(800);
    return {
      data: {
        assessments: [
          MOCK_RESPONSES.green,
          MOCK_RESPONSES.yellow,
          MOCK_RESPONSES.red
        ]
      }
    };
  }
};

export default api;
